zxcalc/quizx

pybindings/Cargo.lock
quizx/Cargo.lock
quizx/Cargo.toml
quizx/src/circuit.rs

Hi, 
I've been working on a parser, type-checker, and interpreter for OpenQASM in Rust ([see here](https://crates.io/crates/openqasm)), and thought it would be nice to integrate it into quizx. It has full support for the OpenQASM 2.0 spec and provides type-checking and detailed error messages.
Compared to the current implementation of circuit parsing in quizx, my crate offers some advantages:
* Ability to expand gate definitions, evaluate parameters and include files
* More flexible parsing of gate parameters (like phases)
* Support for applying a gate to one or more whole registers at once
* Error messages with source location information and automatic formatting
* It also catches some extra errors in general
However, there are also some disadvantages:
* It has several dependencies, …

Use openqasm Crate for QASM Parsing

---

pybindings/src/lib.rs
quizx/src/basic_rules.rs
quizx/src/bin/cnot_anneal.rs
quizx/src/bin/hidden_shift_stabrank.rs
quizx/src/bin/pauli_gadget_stabrank.rs
quizx/src/bin/pauli_gadget_stabrank_met.rs
quizx/src/bin/pauli_gadget_stabrank_ne.rs
quizx/src/bin/pauli_gadget_stabrank_single.rs
quizx/src/bin/read_circuits.rs
quizx/src/bin/spider_chain.rs
quizx/src/bin/test_all.rs
quizx/src/bin/test_one.rs
quizx/src/circuit.rs
quizx/src/decompose.rs
quizx/src/extract.rs
quizx/src/gate.rs
quizx/src/generate.rs
quizx/src/graph.rs
quizx/src/hash_graph.rs
quizx/src/linalg.rs
quizx/src/random_graph.rs
quizx/src/scalar.rs
quizx/src/scalar_old.rs
quizx/src/simplify.rs
quizx/src/tensor.rs
quizx/src/vec_graph.rs

This PR fixes all the warnings produced by `cargo check` and `cargo clippy --all-targets --all-features`.

fix: Lints and warnings

---

Cargo.lock
Cargo.toml
pybindings/quizx/__init__.py
pybindings/quizx/circuit.py
pybindings/quizx/decompose.py
pybindings/quizx/graph.py
pybindings/quizx/simplify.py
pybindings/src/lib.rs
pyproject.toml
quizx/src/scalar.rs
scripts/add_estimates_hs.py

- Updates `pyo3` to `0.21`
- Adds a `module-name` config to maturin, so now the rust bindings are available under `quizx._quizx` in the rest of the code.
This is required to prevent name collisions with the python definitions.
Previous to #18 the bindings where being defined as a separate `libquizx` library, but that causes problems when trying to generate wheels and publish a single package.

fix: Move rust bindings to a `quizx._quizx` submodule

---

pybindings/src/lib.rs
quizx/src/simplify.rs

Gadget fusion doesn't seem to work as it deletes all of the phase gadgets before trying to update the phase of the first gadget. The bug disappears when we leave the first phase gadget undeleted.
```python
import pyzx as zx
def to_quizx(p_g):
r_g = zx.Graph(backend='quizx-vec')
v_map = dict()
for v in p_g.vertices():
new_v = r_g.add_vertex(ty=p_g.type(v), qubit=p_g.qubit(v), row=p_g.row(v), phase=p_g.phase(v))
v_map[v] = new_v
for e in p_g.edges():
new_e = (v_map[e[0]], v_map[e[1]])
r_g.add_edge(new_e, p_g.edge_type(e))
return r_g
c = zx.Circuit(2)
c.add_gate("ZPhase", 0, 0.25)
c.add_gate("CNOT", 1, 0)
c.add_gate("ZPhase", 0, 0.25)
c.add_gate("CNOT", 1, 0)
c.add_gate("ZPhase", 0, 0.25)
c.add_gate("ZPhase", 1, 0.25)
g = c.to_graph()
g.apply_state('++')
g.apply_effect('++')
zx.draw(g, …
```

fix: gadget fusion

---

CONTRIBUTING.md
Cargo.toml
README.md
pyproject.toml
quizx/src/json.rs
stabrank.md

Renames references to "Quantomatic" to the new "zxlang" github organization.

docs: Update links to the renamed organization

---

quizx/src/hash_graph.rs

Removes the unused edge iterator definition from `hash_graph`. The struct uses `graph.rs`'s `EIter` instead.
This caused a linting warning in rust 1.80

chore: Drop duplicated iterator definition

---

README.md
pybindings/README.md
pyproject.toml
quizx/Cargo.toml

Building the source wheels failed due duplicated READMEs.
https://github.com/zxcalc/quizx/actions/runs/11141837093/job/30963545762#step:3:190
This PR writes a better readme for the python package in `pybindings/`, and avoids including the one at the project root.

fix: sdist build config

---

quizx/src/json/scalar.rs
quizx/src/scalar.rs

As @ColbyDeLisle mentioned in issue #63, `pow` refers to powers of two, whereas pyzx's `power2` refers to powers of sqrt(2). This was handled incorrectly in the Exact arm of `JsonScalar::from_scalar`. I have reworked that now so this fixes #63.
I believe that `full_simplify` usually leads to scalars of the form `sqrt(2)^n * exp(m*i*pi/4)` for Clifford+T graphs. I refactored the match arm so that these values are always treated exactly. For other scalars, they are simply split up as `phase` and `floatfactor`.

fix: Fix bug in JsonScalar::from_scalar

---

quizx/src/scalar.rs

In my previous PR I used `num::integer::sqrt(2)` which simply rounded to 1. This is fixed now.

bug: Fix issue in Scalar::phase

---

.github/workflows/pr-title.yml

The check that validates a PR's title was enabled for "main" instead of "master"

ci: Fix disabled pr-title check

---

.github/workflows/wheels.yml

The release workflow ran and built the wheels, but for some reason the `publish` step got skipped -.-'
https://github.com/zxcalc/quizx/actions/runs/11603200919/job/32310138857
This PR simplifies the `if` condition and adds debug info.

ci: Try to debug the release workflow

---

.github/workflows/ci.yml
pyproject.toml
uv.lock

Bumps pyzx from 0.8 to 0.9. [Here ](https://github.com/zxcalc/pyzx/releases/tag/v0.9.0)is the release.
This isn't caught by dependabot because `pyzx` isn't a dev-dependency (see [here](https://github.com/zxcalc/quizx/blob/master/.github/dependabot.yml#L34)).

chore(deps): bump pyzx from 0.8 to 0.9

---

.github/workflows/wheels.yml

`macos-12` workers got deprecated, so the wheel building job hangs forever waiting for a worker.

ci(wheels): Update x86 macos builder to macos-13

---

.github/workflows/release-plz.yml
.github/workflows/semver-checks.yml
release-plz.toml

Sets up `release-plz` to auto-generate release PRs with changelog and crate version updates (similar to the python ones).
Once one of those PRs gets merged, it will automatically generate a new github release for the crate and upload it to crates.io.
I also added a workflow that runs `cargo-semver-checks`, so it detects when the changes in a PR break semver compatibility and we should mark it as such (by adding a `!` in the PR title). These `!`s will be detected by `release-plz` when choosing the next crate version.
I haven't added a crates io api token yet. Tokens can be given permissions to publish new crates and to publish crate-updates separatedly. To avoid any surprises, I prefer to only give automation the latter, so I'll do the first release `0.1.0` manually instead.

ci: Setup crate releases

---

release-please-config.json
release-plz.toml

Gives a clear distinction between both release PRs by adding a 🦀 or 🐍 tag to their title
drive-by: format the release-please yml

ci: mark the release PRs as either rust of python

---

pybindings/src/lib.rs
quizx/src/lib.rs

Looks like I added these to the wrong library, so the docs landing page is empty -.-
https://docs.rs/quizx/0.1.0/quizx/

docs(rs): Add crate documentation

---

quizx/examples/surface_code.rs
quizx/src/basic_rules.rs
quizx/src/circuit.rs
quizx/src/gate.rs
quizx/src/simplify.rs

Added new simplifications `local_gslc_simp` and `local_ap_simp`, which each take a set of nodes and perform simplifications local to those nodes to try to preserve GSLC or AP normal forms, respectively.
The AP form reduction method can be called on-the-fly while generating a graph via `Circuit::to_graph_with_options` with `simplify=true`. This may perform better for some circuits then generating the whole graph at once and applying `clifford_simp`.
BREAKING CHANGE:
* `Circuit::to_graph_with_options` now takes an extra argument `simplify`. Set this to `false` to get the previous behavior.

feat!: converting a circuit to a graph while performing Clifford simplifications

---

quizx/src/equality.rs

- Only compares the graph tensors instead of the circuit tensors as a temporary workaround for: #135
- Equality checker now compares the number of input and output qubits separately instead of just the total number of qubits. (This is a step towards supporting circuits with [ancillae](https://github.com/zxcalc/quizx/issues/111#issuecomment-2889750454).)
BREAKING CHANGE: Introduced a consistent naming convention for equality related methods.

feat!: better equality checker

---

quizx/Cargo.toml
quizx/benches/basics.rs
quizx/benches/decomposer.rs
quizx/benches/simplifier.rs

Closes #134 
There are 3 benchmark files, `basics.rs`, `simplifier.rs`, `decomposer.rs`. 
the test files are specified in `get_test_files`, so we can add and remove qasm test files as we wish.

test: add benchmarks

---

quizx/src/decompose.rs

BREAKING CHANGE: Added enum variants `Driver::SpiderCutting` and `Decomp::SpiderCuttingDecomp`
closes #115

feat!: Add spider-cutting decomposition

---

.github/workflows/ci.yml
Cargo.lock
quizx/Cargo.toml
quizx/src/circuit.rs
quizx/src/detection_webs.rs
quizx/src/extract.rs
quizx/src/graph.rs
quizx/src/lib.rs

The F2-matrix implementation in `linalg.rs` has been replaced with `BitMatrix` from the [bitgauss](https://github.com/akissinger/bitgauss) library, which should be significantly faster for big matrices.

feat: use bitgauss library for fast F2 linear algebra
